version: '2'

services:

  proxy:
    image: nginx:alpine
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    volumes:
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html/
      - ./data/proxy/certs/:/etc/nginx/certs:ro
    networks:
      - default
      - ambassador
    lables:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    restart: unless-stopped
    networks:
      - default
      - ambassador
    depends_on:
      - proxy
    volumes_from:
      - proxy
    volumes:
      - ./config/docker-gen/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen=true"
    command: ["-notify-sighup", "proxy", "-watch", "-wait", "5s:30s", "/etc/docker-gen/templates/nginx.tmpl", "/etc/nginx/conf.d/default.conf"]

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: unless-stopped
    networks:
      - default
      - ambassador
    depends_on:
      - proxy
      - docker-gen
    volumes_from:
      - proxy
    volumes:
      - ./data/proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=docker-gen
      - NGINX_PROXY_CONTAINER=proxy

  portainer:
    image: portainer/portainer
    environment:
      - VIRTUAL_HOST="manage.steem.racing"
      - LETSENCRYPT_HOST="manage.steem.racing"
      - LETSENCRYPT_EMAIL="anybucket@outlook.com"
networks:
  default:
  ambassador:
    external:
      name: ambassador
